name: Reusable workflow example

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      API_TOKEN:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Print received values
        run: |
          echo "Valor do Input 'config-path': ${{ inputs.config-path }}"
          echo "O Secret 'token' será mascarado: ${{ secrets.token }}"

      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.token }}
          configuration-path: ${{ inputs.config-path }}
