name: Reusable workflow example

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      API_TOKEN:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Print received values
        run: |
          echo "Valor do Input 'config-path': ${{ inputs.version }}"
          echo "O Secret 'token' será mascarado: ${{ secrets.API_TOKEN }}"

      - uses: actions/labeler@v4
        with:
          repo-version: ${{ inputs.version }}
          secret_apitoken: ${{ secrets.API_TOKEN }}
